INSERT INTO public.administrator (user_id, duty) VALUES (1180, 'Lecturer, higher education468');
INSERT INTO public.administrator (user_id, duty) VALUES (26, 'Sports coach408');
INSERT INTO public.administrator (user_id, duty) VALUES (2220, 'Medical sales representative134');
INSERT INTO public.administrator (user_id, duty) VALUES (2950, 'Designer, interior/spatial389');
INSERT INTO public.administrator (user_id, duty) VALUES (2626, 'Land363');
INSERT INTO public.administrator (user_id, duty) VALUES (745, 'Engineer, materials197');
INSERT INTO public.administrator (user_id, duty) VALUES (10, 'Educational psychologist115');
INSERT INTO public.administrator (user_id, duty) VALUES (578, 'Research scientist (maths)429');
INSERT INTO public.administrator (user_id, duty) VALUES (2431, 'Operational researcher458');
INSERT INTO public.administrator (user_id, duty) VALUES (1044, 'Careers adviser124');
INSERT INTO public.administrator (user_id, duty) VALUES (1294, 'Geneticist, molecular470');
INSERT INTO public.administrator (user_id, duty) VALUES (1144, 'Minerals surveyor357');
INSERT INTO public.administrator (user_id, duty) VALUES (365, 'Call centre manager358');
INSERT INTO public.administrator (user_id, duty) VALUES (1679, 'Illustrator68');
INSERT INTO public.administrator (user_id, duty) VALUES (2145, 'Producer, television/film/video21');
INSERT INTO public.administrator (user_id, duty) VALUES (2029, 'Optician, dispensing204');
INSERT INTO public.administrator (user_id, duty) VALUES (1763, 'Adult guidance worker244');
INSERT INTO public.administrator (user_id, duty) VALUES (35, 'Land320');
INSERT INTO public.administrator (user_id, duty) VALUES (2845, 'Passenger transport manager130');
INSERT INTO public.administrator (user_id, duty) VALUES (1391, 'Facilities manager43');
INSERT INTO public.administrator (user_id, duty) VALUES (2509, 'Primary school teacher341');
INSERT INTO public.administrator (user_id, duty) VALUES (229, 'Occupational hygienist248');
INSERT INTO public.administrator (user_id, duty) VALUES (1384, 'Scientist, clinical (histocompatibility and immunogenetics)187');
INSERT INTO public.administrator (user_id, duty) VALUES (391, 'Librarian, academic311');
INSERT INTO public.administrator (user_id, duty) VALUES (2475, 'Air cabin crew254');
INSERT INTO public.administrator (user_id, duty) VALUES (452, 'Surveyor, quantity217');
INSERT INTO public.administrator (user_id, duty) VALUES (2741, 'Accountant, chartered management188');
INSERT INTO public.administrator (user_id, duty) VALUES (901, 'Office manager173');
INSERT INTO public.administrator (user_id, duty) VALUES (2591, 'Building control surveyor395');
INSERT INTO public.administrator (user_id, duty) VALUES (642, 'Primary school teacher371');
INSERT INTO public.administrator (user_id, duty) VALUES (2843, 'Diplomatic Services operational officer403');
INSERT INTO public.administrator (user_id, duty) VALUES (329, 'Immigration officer313');
INSERT INTO public.administrator (user_id, duty) VALUES (822, 'Secretary/administrator349');
INSERT INTO public.administrator (user_id, duty) VALUES (293, 'Learning disability nurse420');
INSERT INTO public.administrator (user_id, duty) VALUES (23, 'Advertising account executive18');
INSERT INTO public.administrator (user_id, duty) VALUES (289, 'Chiropodist416');
INSERT INTO public.administrator (user_id, duty) VALUES (2279, 'Research officer, government277');
INSERT INTO public.administrator (user_id, duty) VALUES (279, 'Geneticist, molecular494');
INSERT INTO public.administrator (user_id, duty) VALUES (1546, 'Surgeon289');
INSERT INTO public.administrator (user_id, duty) VALUES (897, 'Operational researcher451');
INSERT INTO public.administrator (user_id, duty) VALUES (348, 'Magazine features editor499');
INSERT INTO public.administrator (user_id, duty) VALUES (2386, 'Restaurant manager, fast food90');
INSERT INTO public.administrator (user_id, duty) VALUES (1194, 'Phytotherapist226');
INSERT INTO public.administrator (user_id, duty) VALUES (796, 'Administrator75');
INSERT INTO public.administrator (user_id, duty) VALUES (1279, 'Market researcher451');
INSERT INTO public.administrator (user_id, duty) VALUES (1484, 'Nurse, children''s231');
INSERT INTO public.administrator (user_id, duty) VALUES (2928, 'Designer, ceramics/pottery221');
INSERT INTO public.administrator (user_id, duty) VALUES (1678, 'Charity officer376');
INSERT INTO public.administrator (user_id, duty) VALUES (1496, 'Retail banker217');
INSERT INTO public.administrator (user_id, duty) VALUES (2930, 'Multimedia specialist252');