INSERT INTO public.domain (domain_id, domain_name) VALUES (1, 'Designer, furniture');
INSERT INTO public.domain (domain_id, domain_name) VALUES (2, 'International aid/development worker');
INSERT INTO public.domain (domain_id, domain_name) VALUES (3, 'Publishing rights manager');
INSERT INTO public.domain (domain_id, domain_name) VALUES (4, 'Clinical cytogeneticist');
INSERT INTO public.domain (domain_id, domain_name) VALUES (5, 'Architect');
INSERT INTO public.domain (domain_id, domain_name) VALUES (6, 'Oceanographer');
INSERT INTO public.domain (domain_id, domain_name) VALUES (7, 'Database administrator');
INSERT INTO public.domain (domain_id, domain_name) VALUES (8, 'Solicitor');
INSERT INTO public.domain (domain_id, domain_name) VALUES (9, 'Patent examiner');
INSERT INTO public.domain (domain_id, domain_name) VALUES (10, 'Insurance risk surveyor');
INSERT INTO public.domain (domain_id, domain_name) VALUES (11, 'Equality and diversity officer');
INSERT INTO public.domain (domain_id, domain_name) VALUES (12, 'Special effects artist');
INSERT INTO public.domain (domain_id, domain_name) VALUES (13, 'Call centre manager');
INSERT INTO public.domain (domain_id, domain_name) VALUES (14, 'Futures trader');
INSERT INTO public.domain (domain_id, domain_name) VALUES (15, 'Commercial art gallery manager');
INSERT INTO public.domain (domain_id, domain_name) VALUES (16, 'Investment banker, corporate');
INSERT INTO public.domain (domain_id, domain_name) VALUES (17, 'Manufacturing engineer');
INSERT INTO public.domain (domain_id, domain_name) VALUES (18, 'Pharmacist, community');
INSERT INTO public.domain (domain_id, domain_name) VALUES (19, 'IT trainer');
INSERT INTO public.domain (domain_id, domain_name) VALUES (20, 'Engineer, production');