INSERT INTO public.reviewer (user_id, academic_title) VALUES (2000, 'Paramedic62');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2731, 'Teacher, secondary school248');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2930, 'Travel agency manager210');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (866, 'Nurse, adult22');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2525, 'Claims inspector/assessor285');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1876, 'Engineer, materials369');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (459, 'Arts administrator313');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1082, 'Museum/gallery exhibitions officer428');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2830, 'Proofreader245');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1729, 'TEFL teacher391');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (878, 'Building control surveyor16');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1711, 'Academic librarian177');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (523, 'Interpreter490');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (882, 'Contractor260');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1188, 'Charity officer416');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (764, 'Art therapist285');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1519, 'Homeopath416');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (792, 'Designer, textile254');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2260, 'Editor, magazine features278');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2925, 'Financial risk analyst306');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1178, 'Scientist, research (maths)305');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1038, 'Further education lecturer171');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2521, 'Administrator, arts132');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1249, 'Oncologist182');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2650, 'Government social research officer189');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1300, 'Lobbyist69');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1794, 'Hydrologist177');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1078, 'Armed forces logistics/support/administrative officer382');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (829, 'Nurse, children''s120');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1636, 'Designer, exhibition/display490');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1509, 'Cartographer81');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1268, 'Geographical information systems officer453');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (499, 'Advertising copywriter438');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2062, 'Clothing/textile technologist101');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (326, 'Fish farm manager439');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1660, 'Advertising account planner257');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1587, 'Optometrist88');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1034, 'Merchandiser, retail128');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (129, 'Therapist, horticultural411');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2873, 'Public house manager59');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (183, 'Therapeutic radiographer280');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1324, 'Advertising account executive289');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1532, 'Arts development officer99');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1021, 'Higher education lecturer302');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2190, 'Holiday representative118');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (144, 'Curator366');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (788, 'Physiological scientist463');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1728, 'Editorial assistant291');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (1777, 'Designer, television/film set251');
INSERT INTO public.reviewer (user_id, academic_title) VALUES (2481, 'Engineer, mining222');