truncate table "user",
    university,
    participant,
    welcomepack,
    ticket,
    lecture,
    participation,
    classroom,
    timetable,
    domain,
    paper,
    reviewer,
    grade,
    administrator,
    event,
    supervision,
    domain_reviewer;
